blueprint:
  name: Time controlled switch
  description: Keep the selected switch according to a schedule.
  domain: automation
  input:
    switch:
      name: Target switch
      description: The switch to control.
      selector:
        entity:
          domain:
            - switch
    schedule:
      name: Schedule
      description: The schedule controlling the switch.
      selector:
        entity:
          domain:
            - schedule

trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: !input switch
  - platform: state
    entity_id: !input schedule

variables:
  switch_entity: !input switch
  schedule_entity: !input schedule

action:
  - if:
      - '{{ states(schedule_entity) == "off" }}'
    then:
      - action: switch.turn_off
        target:
          entity_id: "{{ switch_entity }}"
    else:
      - action: switch.turn_on
        target:
          entity_id: "{{ switch_entity }}"

mode: single
max_exceeded: silent
